version: '3.8'
services:
  db:
    container_name: ds-review-db
    image: postgres:13.4
    restart: on-failure
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=devdb
    ports:
      - "5432:5432"
    networks:
      - internal
  backend:
    container_name: ds-review-backend
    image: gitlab.fit.cvut.cz:5050/ds-review/backend:master
    entrypoint: /bin/bash
    command: -c "source /venv/bin/activate && cd app/app && python -m main"
    environment:
      - POSTGRES_SERVER=db
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - internal
  frontend:
    container_name: ds-review-frontend
    image: gitlab.fit.cvut.cz:5050/ds-review/frontend:master
    restart: on-failure
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - internal
networks:
  internal:


