name: buk-reservation
channels:
  - conda-forge
dependencies:
  - python=3.11.8
  - fastapi=0.110.0
  - uvicorn=0.27.1
  - websockets=12.0
  - jinja2=3.1.4
  - pylint=3.2.1
  - pandas=2.2.2
  - passlib=1.7.4
  - pytest=8.2.0
  - sqlalchemy=2.0.27
  - psycopg2=2.9.9
  - python-dotenv=1.0.1
  - python-jose=3.3.0
  - python-multipart=0.0.9
  - duckdb-engine=0.7.0
  - mypy=1.10.0
  - httpx=0.27.0
  - conda-pack=0.7.1
  - conda-lock=2.5.5
  - pytest-cov=5.0.0
  - pydantic-settings=2.2.1
  - pytz=2024.1
  - google-api-python-client=2.120.0
  - google-auth-oauthlib=1.2.0
platforms:
  - linux-64
  - win-64
  - osx-arm64

