services:
  - docker:dind

image: node:18.15.0

stages:
  - dependencies
  - test
  - build
  - publish
  - doc
  - analysis

install_dependencies:
  stage: dependencies
  script:
    - npm install
  only:
    - master
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules

publish_image:
  stage: publish
  image: quay.io/buildah/stable
  variables:
    # Use vfs with buildah. Docker offers overlayfs as a default, but Buildah
    # cannot stack overlayfs on top of another overlayfs filesystem.
    STORAGE_DRIVER: vfs
    # Write all image metadata in the docker format, not the standard OCI format.
    # Newer versions of docker can handle the OCI format, but older versions, like
    # the one shipped with Fedora 30, cannot handle the format.
    BUILDAH_FORMAT: docker
    FQ_IMAGE_NAME: "$CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG"
  before_script:
    # GitLab Container Registry credentials taken from the
    # [predefined CI/CD variables](../variables/index.md#predefined-cicd-variables)
    # to authenticate to the registry.
    - buildah login -u "$CI_REGISTRY_USER" -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - buildah images
    - buildah build -t $FQ_IMAGE_NAME -f Dockerfile .
    - buildah images
    - buildah login -u "$CI_REGISTRY_USER" -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - buildah push $FQ_IMAGE_NAME

build_image:
  stage: build
  script:
    - npm link @angular/cli@15.0.0
    - npm run build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/dist
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

compodoc:
  stage: doc
  script:
    - npm install -g @compodoc/compodoc
    - compodoc -p tsconfig.json
  only:
    - master
  artifacts:
    paths:
      - $CI_PROJECT_DIR/documentation

eslint_analysis:
  stage: analysis
  script:
    - npm install -g @angular/cli
    - npm install
    - npm install -g eslint-html-reporter
    - ./node_modules/.bin/eslint "src/**/*.ts" -f html -o eslint-report.html || true
  artifacts:
    paths:
      - eslint-report.html
    expire_in: 1 week